default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_api_project_development

test:
  <<: *default
  database: rails_api_project_test

production:
  <<: *default
  database: rails_api_project_production
  username: rails_api_project
  password: <%= ENV['RAILS_API_PROJECT_DATABASE_PASSWORD'] %>
